### ISSUE TITLE
What the Tab Key does ?

### ISSUE THREAD

**Issue by cgarrotti** [waffdev/EZ-Delivery#1]
What the Tab Key does ?

**Comment by waffdev** [comment]
Debug key I completely forgot to remove! Thanks for that I’ll fix it when I’ve got time later

**Comment by waffdev** [comment]
All fixed in 1.5.2a
Was debating actually uploading it until I fix any other bugs or add new features but thought I best fix it right away incase it causes some errors as the AutoRack could be called when it's not supposed to be.
